### ISSUE TITLE
Is this project no longer stable?

### ISSUE THREAD

**Issue by richjava** [tabvn/loopbackCMS#7]
This project looks amazing but I'm getting these errors when starting the apps:

**For api:**

-------------------------------------------------------------

npm start

> api@1.0.0 start D:\Projects\success-stories\loopbackCMS\api
> node .

users settings.validateUpsert was overriden to false
media settings.validateUpsert was overriden to false
D:\Projects\success-stories\loopbackCMS\api\node_modules\loopback-datasource-juggler\lib\datas
ource.js:596
    throw error;
    ^

Error: polymorphic belongsTo relation: avatar does not expect param `model`
    at validateRelation (D:\Projects\success-stories\loopbackCMS\api\node_modules\loopback-dat
asource-juggler\lib\datasource.js:594:17)

-------------------------------------------------------------

**For backend:**

-------------------------------------------------------------

`PS D:\Projects\success-stories\loopbackCMS\backend> npm start

> backend-app@0.0.0 start D:\Projects\success-stories\loopbackCMS\backend
> ng serve

** NG Live Development Server is running on http://localhost:4200 **
 86% hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\depende
ncies\HarmonyExportImportedSpecifierDependency.js:144:8)
    at D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\DependenciesBlock
.js:32:20)
    at NormalModule.Module.updateHash (D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (D:\Projects\success-stories\loopbackCMS\backend\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)`

-------------------------------------------------------------

**For frontend:**

-------------------------------------------------------------

`> frontend@0.0.0 start D:\Projects\success-stories\loopbackCMS\frontend
> ng serve

** NG Live Development Server is running on http://localhost:4200 **
Hash: 366ce29ae6193cf48bfc
Time: 32139ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 160 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 236 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.72 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda w
ith a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in D:/Projects/success-stories
/loopbackCMS/backend/node_modules/@angular/core/core.d.ts, resolving symbol ApiModule in D:/Projects/success-stories/loopbackCMS/backend/src
/app/shared/services/api.module.ts, resolving symbol ApiModule in D:/Projects/success-stories/loopbackCMS/backend/src/app/shared/services/ap
i.module.ts
webpack: Failed to compile.`

**Comment by MROALI** [comment]
Hello @richjava, for the api, you need to remove the parameter **model** from the relation object in different db models in which  belongsTo and polymorphic relation is defined.

example  : 
in taxonomy-node.json 
    "node": {
      "type": "belongsTo",
      "as": "taxonomies",
        -----"model": "node", ---    this line to be removed 
       "polymorphic": {
        "foreignKey": "refId",
        "discriminator": "refType"
      }
    }

See the documentation for more info : 
https://loopback.io/doc/en/lb3/Polymorphic-relations.html
