### ISSUE TITLE
polymorphic belongsTo relation: avatar does not expect param `model`

### ISSUE THREAD

**Issue by philipsagala** [tabvn/loopbackCMS#8]
I get this error when starting API

> users settings.validateUpsert was overriden to false
media settings.validateUpsert was overriden to false
/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:597
    throw error;
    ^

Error: polymorphic belongsTo relation: avatar does not expect param `model`
    at validateRelation (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:595:17)
    at /Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:515:7
    at Array.forEach (<anonymous>)
    at DataSource.defineRelations (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:511:28)
    at DataSource.setupDataAccess (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:648:8)
    at DataSource.attach (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/datasource.js:882:8)
    at Function.ModelClass.attachTo (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-datasource-juggler/lib/model-builder.js:382:16)
    at Registry.configureModel (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback/lib/registry.js:235:15)
    at configureModel (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback/lib/application.js:546:16)
    at Function.app.model (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback/lib/application.js:126:5)
    at /Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-boot/lib/executor.js:203:9
    at Array.forEach (<anonymous>)
    at setupModels (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-boot/lib/executor.js:199:23)
    at execute (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/Users/philiprichard/Frontends/loopbackCMS/api/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/Users/philiprichard/Frontends/loopbackCMS/api/server/server.js:31:1)

**Comment by minasvisual** [comment]
same here

**Comment by Rezende123** [comment]
me to
